package api

import (
	"context"
	"errors"
	"net/http"

	"github.com/danielgtaylor/huma/v2"

	"go.kenn.io/docbank/internal/loadfile"
	"go.kenn.io/docbank/internal/store"
)

// PackagePage is one stable package-identity page. NextAfter is the opaque
// package ID callers may pass back as after; an exact final page may still
// produce a cursor and is followed by an empty page.
type PackagePage struct {
	Items     []PackageSummary `json:"items" maxItems:"250"`
	Direction string           `json:"direction,omitempty" enum:"received,produced"`
	After     string           `json:"after,omitempty"`
	NextAfter string           `json:"next_after,omitempty"`
	Limit     int              `json:"limit" minimum:"1" maximum:"250"`
}

// PackageSummary carries package identity and immutable authority hashes
// without repeating retained profile and mapping JSON on every list row.
type PackageSummary struct {
	PackageID            string `json:"package_id" format:"uuid"`
	SnapshotID           string `json:"snapshot_id,omitempty"`
	Direction            string `json:"direction" enum:"received,produced"`
	PackageName          string `json:"package_name"`
	PartyLabel           string `json:"party_label"`
	ProfileSHA256        string `json:"profile_sha256"`
	MappingSHA256        string `json:"mapping_sha256"`
	ManifestSHA256       string `json:"manifest_sha256"`
	ManifestBlobSHA256   string `json:"manifest_blob_sha256"`
	PredecessorPackageID string `json:"predecessor_package_id,omitempty"`
	Relation             string `json:"relation,omitempty"`
	IngestID             string `json:"ingest_id,omitempty"`
	ExportPlanID         string `json:"export_plan_id,omitempty"`
	ProducedOn           string `json:"produced_on,omitempty"`
	State                string `json:"state"`
	CreatedAt            string `json:"created_at" format:"date-time"`
	CompletedAt          string `json:"completed_at,omitempty"`
	MemberCount          int    `json:"member_count" minimum:"0"`
	PageCount            int    `json:"page_count" minimum:"0"`
}

// PackageBrowseVolume preserves the sender root and the approved mapped root.
type PackageBrowseVolume struct {
	Ordinal            int    `json:"ordinal" minimum:"1"`
	VolumeName         string `json:"volume_name"`
	DeclaredRoot       string `json:"declared_root"`
	MappedRoot         string `json:"mapped_root"`
	ResolvedRootSHA256 string `json:"resolved_root_sha256"`
}

// PackageDetail adds retained profile and mapping authority to the summary.
type PackageDetail struct {
	PackageSummary

	ProfileJSON string                `json:"profile_json"`
	MappingJSON string                `json:"mapping_json"`
	Volumes     []PackageBrowseVolume `json:"volumes" maxItems:"64"`
}

// PackageMemberPage preserves the immutable member ordinal as its page key.
type PackageMemberPage struct {
	Items            []store.CollectionSnapshotMember `json:"items" maxItems:"250"`
	AfterOrdinal     int                              `json:"after_ordinal" minimum:"0"`
	NextAfterOrdinal int                              `json:"next_after_ordinal,omitempty" minimum:"0"`
	Limit            int                              `json:"limit" minimum:"1" maximum:"250"`
}

// PackageLabelCandidatePage does not collapse labels reused across packages
// or occurrences. NextCursor is generated by the store from the full identity.
type PackageLabelCandidatePage struct {
	Items      []store.PackageLabelRow `json:"items" maxItems:"250"`
	NextCursor string                  `json:"next_cursor,omitempty"`
	Limit      int                     `json:"limit" minimum:"1" maximum:"250"`
}

// PackageTimelineInputPage retains exact sender rows and their declared zone.
type PackageTimelineInputPage struct {
	Items          []store.PackageTimelineInput `json:"items" maxItems:"250"`
	AfterRowID     string                       `json:"after_row_id,omitempty"`
	NextAfterRowID string                       `json:"next_after_row_id,omitempty"`
	Limit          int                          `json:"limit" minimum:"1" maximum:"250"`
}

// PackageFieldCatalog is the closed set of canonical mapping targets and
// accepted sender aliases.
type PackageFieldCatalog struct {
	Fields []loadfile.CatalogEntry `json:"fields" maxItems:"64"`
}

func registerPackageBrowseRoutes(api huma.API, d Deps) {
	huma.Register(api, huma.Operation{
		OperationID: "listPackages", Method: http.MethodGet, Path: "/api/v1/packages",
		Summary: "List received and produced packages",
	}, func(ctx context.Context, input *struct {
		Direction string `query:"direction" enum:"received,produced"`
		After     string `query:"after" maxLength:"36"`
		Limit     int    `query:"limit" default:"100" minimum:"1" maximum:"250"`
	}) (*struct{ Body PackagePage }, error) {
		items, err := d.Store.Packages(ctx, input.Direction, input.After, input.Limit)
		if err != nil {
			return nil, packageBrowseError(err)
		}
		views := make([]PackageSummary, 0, len(items))
		for _, item := range items {
			views = append(views, packageSummary(item))
		}
		body := PackagePage{Items: views, Direction: input.Direction, After: input.After, Limit: input.Limit}
		if len(items) == input.Limit {
			body.NextAfter = items[len(items)-1].PackageID
		}
		return &struct{ Body PackagePage }{Body: body}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "getPackage", Method: http.MethodGet, Path: "/api/v1/packages/by-id/{package_id}",
		Summary: "Read one package identity and state",
	}, func(ctx context.Context, input *struct {
		PackageID string `path:"package_id"`
	}) (*struct{ Body PackageDetail }, error) {
		pkg, err := d.Store.Package(ctx, input.PackageID)
		if err != nil {
			return nil, FromStoreError(err)
		}
		return &struct{ Body PackageDetail }{Body: packageDetail(pkg)}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "listPackageMembers", Method: http.MethodGet,
		Path: "/api/v1/packages/by-id/{package_id}/members", Summary: "List immutable package members",
	}, func(ctx context.Context, input *struct {
		PackageID    string `path:"package_id"`
		AfterOrdinal int    `query:"after_ordinal" default:"0" minimum:"0"`
		Limit        int    `query:"limit" default:"100" minimum:"1" maximum:"250"`
	}) (*struct{ Body PackageMemberPage }, error) {
		items, err := d.Store.PackageMembers(ctx, input.PackageID, input.AfterOrdinal, input.Limit)
		if err != nil {
			return nil, packageBrowseError(err)
		}
		if items == nil {
			items = []store.CollectionSnapshotMember{}
		}
		body := PackageMemberPage{Items: items, AfterOrdinal: input.AfterOrdinal, Limit: input.Limit}
		if len(items) == input.Limit {
			body.NextAfterOrdinal = items[len(items)-1].Ordinal
		}
		return &struct{ Body PackageMemberPage }{Body: body}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "listPackageLabelCandidates", Method: http.MethodGet,
		Path:    "/api/v1/packages/label-candidates",
		Summary: "Find every package-scoped candidate for an exact label",
	}, func(ctx context.Context, input *struct {
		Label      string `query:"label" required:"true" minLength:"1" maxLength:"256"`
		PackageID  string `query:"package_id" maxLength:"36"`
		LabelSet   string `query:"label_set" maxLength:"256"`
		Provenance string `query:"provenance" enum:"received,assigned"`
		Cursor     string `query:"cursor" maxLength:"2048"`
		Limit      int    `query:"limit" default:"100" minimum:"1" maximum:"250"`
	}) (*struct{ Body PackageLabelCandidatePage }, error) {
		items, next, err := d.Store.PackageLabelCandidates(ctx, input.Label, input.PackageID,
			input.LabelSet, input.Provenance, input.Cursor, input.Limit)
		if err != nil {
			return nil, packageBrowseError(err)
		}
		if items == nil {
			items = []store.PackageLabelRow{}
		}
		return &struct{ Body PackageLabelCandidatePage }{Body: PackageLabelCandidatePage{
			Items: items, NextCursor: next, Limit: input.Limit,
		}}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "listPackageFieldCatalog", Method: http.MethodGet,
		Path: "/api/v1/packages/field-catalog", Summary: "List canonical package fields and sender aliases",
	}, func(context.Context, *struct{}) (*struct{ Body PackageFieldCatalog }, error) {
		return &struct{ Body PackageFieldCatalog }{Body: PackageFieldCatalog{Fields: loadfile.FieldCatalog()}}, nil
	})

	huma.Register(api, huma.Operation{
		OperationID: "listPackageTimelineInputs", Method: http.MethodGet,
		Path:    "/api/v1/packages/by-id/{package_id}/timeline-inputs",
		Summary: "List retained sender rows for explicit timeline parsing",
	}, func(ctx context.Context, input *struct {
		PackageID  string `path:"package_id"`
		AfterRowID string `query:"after_row_id" maxLength:"64"`
		Limit      int    `query:"limit" default:"100" minimum:"1" maximum:"250"`
	}) (*struct{ Body PackageTimelineInputPage }, error) {
		items, err := d.Store.PackageTimelineInputs(ctx, input.PackageID, input.AfterRowID, input.Limit)
		if err != nil {
			return nil, packageBrowseError(err)
		}
		if items == nil {
			items = []store.PackageTimelineInput{}
		}
		body := PackageTimelineInputPage{Items: items, AfterRowID: input.AfterRowID, Limit: input.Limit}
		if len(items) == input.Limit {
			body.NextAfterRowID = items[len(items)-1].RowID
		}
		return &struct{ Body PackageTimelineInputPage }{Body: body}, nil
	})
}

func packageSummary(pkg store.Package) PackageSummary {
	return PackageSummary{
		PackageID: pkg.PackageID, SnapshotID: pkg.SnapshotID, Direction: pkg.Direction,
		PackageName: pkg.PackageName, PartyLabel: pkg.PartyLabel, ProfileSHA256: pkg.ProfileSHA256,
		MappingSHA256: pkg.MappingSHA256, ManifestSHA256: pkg.ManifestSHA256,
		ManifestBlobSHA256: pkg.ManifestBlobSHA256, PredecessorPackageID: pkg.PredecessorPackageID,
		Relation: pkg.Relation, IngestID: pkg.IngestID, ExportPlanID: pkg.ExportPlanID,
		ProducedOn: pkg.ProducedOn, State: pkg.State, CreatedAt: pkg.CreatedAt,
		CompletedAt: pkg.CompletedAt, MemberCount: pkg.MemberCount, PageCount: pkg.PageCount,
	}
}

func packageDetail(pkg store.Package) PackageDetail {
	volumes := make([]PackageBrowseVolume, 0, len(pkg.Volumes))
	for _, volume := range pkg.Volumes {
		volumes = append(volumes, PackageBrowseVolume{
			Ordinal: volume.Ordinal, VolumeName: volume.VolumeName, DeclaredRoot: volume.DeclaredRoot,
			MappedRoot: volume.MappedRoot, ResolvedRootSHA256: volume.ResolvedRootSHA256,
		})
	}
	return PackageDetail{PackageSummary: packageSummary(pkg), ProfileJSON: pkg.ProfileJSON,
		MappingJSON: pkg.MappingJSON, Volumes: volumes}
}

func packageBrowseError(err error) error {
	if errors.Is(err, store.ErrPackageConflict) {
		return NewError(http.StatusUnprocessableEntity, "invalid_package_query",
			"The package browse query or cursor is invalid.")
	}
	return FromStoreError(err)
}
